project_id = "nsowlnpntphxwykzbwmc"

[functions.generate-training-session]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.generate-nutrition-plan]
verify_jwt = true

[functions.generate-training-plan]
verify_jwt = true

[functions.send-support-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.chat-alex]
verify_jwt = true

[functions.chat-julie]
verify_jwt = true
